config:
  backup: true
  create: true
  dotpath: .
dotfiles:
  d_vim:
    dst: ~/.vim
    src: vim/vim
    link: true
  f_vimrc:
    dst: ~/.vimrc
    src: vim/vimrc
    link: true
    actions:
      - vim-plug
      - vim-plug-install
  f_bashrc:
    dst: ~/.bashrc
    src: bash/bashrc
    link: true
  f_bash_colors:
    dst: ~/.bash_colors
    src: bash/bash_colors
    link: true
  f_bash_logout:
    dst: ~/.bash_logout
    src: bash/bash_logout
    link: true
  f_bash_prompt:
    dst: ~/.bash_prompt
    src: bash/bash_prompt
    link: true
profiles:
  Benjen:
    dotfiles:
      include:
        - vim
  vim:
    dotfiles:
      - f_vimrc
      - d_vim
  bash:
    dotfiles:
      - f_bashrc
      - f_bash_colors
      - f_bash_logout
      - f_bash_prompt
actions:
  vim-plug: "mkdir -p ~/.vim/autoload ~/.vim/undo && curl -sfLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 2>&1 >/dev/null"
  vim-plug-install: vim +'PlugInstall --sync' +qall
