config:
  backup: true
  create: true
  dotpath: .
dotfiles:
  d_vim:
    dst: ~/.vim
    link: true
    src: vim/vim
  f_vimrc:
    dst: ~/.vimrc
    link: true
    src: vim/vimrc
    actions:
            - vim-plug
            - vim-plug-install
profiles:
  Benjen:
    dotfiles:
    include:
    - vim
  vim:
    dotfiles:
    - f_vimrc
    - d_vim
actions:
  vim-plug: "mkdir -p ~/.vim/{autoload,undo} && curl -sfLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 2>&1 >/dev/null"
  vim-plug-install: vim +'PlugInstall --sync' +qall
