#!/bin/bash
STOWOPT="--ignore=ignore --ignore=default"

howto() {
    echo "${0#*/}: Unknown package."
    exit 1
}

main() {
    [[ -d $1 ]] || howto
    pkgname=$1
    host=$(hostname)

    defaults=$(find "$pkgname" -iname "*\.default")

    for default in $defaults ; do
        fname=${default%.default}
        cp "$default" "$fname"
        if [[ -f "${fname}.${host}.ignore" ]] ; then
            IFS=" ="
            while read -r option ; do
                optionarr=($option)
                sed -Ei "s/^${optionarr[0]}\s+.*\$/$option/" "$fname"
            done < "${fname}.${host}.ignore"
        fi
    done

    stow $STOWOPT "$pkgname"
}

main "$@"

